f = open("./fileFiocco.txt", "w")

import turtle
snow = turtle.Turtle()
finestra = turtle.Screen()

for _ in range(8):
    snow.forward(250)
    f.write("forward:250\n")
    snow.left(45)
    f.write("left:45\n")
    snow.forward(20)
    f.write("forward:20\n")
    snow.backward(20)
    f.write("backward:20\n")
    snow.right(90)
    f.write("right:90\n")
    snow.forward(20)
    f.write("forward:20\n")
    snow.backward(20)
    f.write("backward:20\n")
    snow.left(45)
    f.write("left:45\n")
    snow.backward(250)
    f.write("backward:250\n")
    snow.left(45)
    f.write("left:45\n")

snow.backward(100)
f.write("backward:100\n")
snow.right(90)
f.write("right:90\n")
snow.circle(100)
f.write("circle:100\n")
snow.right(90)
f.write("right:90\n")
snow.forward(100)
f.write("forward:100\n")
snow.left(90)
f.write("left:90\n")
snow.circle(200)
f.write("circle:200\n")

finestra.exitonclick()
f.close()

